---
name: kaniko-build-CI
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    container:
      image: ixxel/multi-tools-alpine:latest
      options: --privileged
    steps:
    - name: Git clone repo
      uses: actions/checkout@v2
    - name: Kaniko build docker image
      uses: ixxeL-actions/kaniko-build@main
      with:
        img-name: test
        tag: v1.0
        file: '""'
        format: oci
        build-arg: ''
        working-dir: .
        target-dir: .